parameters:
  terraformDirectory: $(System.DefaultWorkingDirectory)
  environmentSubscription: ''

steps:
- task: TerraformTaskV2@2
  displayName: Terraform Apply
  name: TerraformApply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: ${{parameters.terraformDirectory}}
    environmentServiceNameAzureRM: ${{parameters.environmentSubscription}}