parameters:
  terraformDirectory: $(System.DefaultWorkingDirectory)
  environmentSubscription: ''
  # If the whole plan should be destroyed then don't pass anything in
  resourcesToDestroy: []
  
steps:
# If no specific resources passed in to destroy then destroy the whole thing
- ${{ if eq(length(parameters.resourcesToDestroy), 0) }}:
  - task: TerraformTaskV2@2
    displayName: Terraform Destroy
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: ${{parameters.terraformDirectory}}
      environmentServiceNameAzureRM: ${{parameters.environmentSubscription}}
# If some resources have been passed in then we only want to destroy them, so loop through and call destroy for each one
- ${{ if gt(length(parameters.resourcesToDestroy), 0) }}:
  - ${{ each resource in parameters.resourcesToDestroy }}:
    - task: TerraformTaskV2@2
      displayName: Terraform Destroy ${{ resource }})
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: ${{parameters.terraformDirectory}}
        environmentServiceNameAzureRM: ${{parameters.environmentSubscription}}
        commandOptions: -target=${{ resource }}