parameters:
  terraformDirectory: $(System.DefaultWorkingDirectory)
  terraformVersion: '0.12.21'
  resourceName: ''
  environmentId: ''
  backendSubscription: ''
  backendResourceGroup: ''
  backendStorageAccount: ''

steps:
- task: TerraformInstaller@0
  displayName: Terraform Install
  inputs: 
    terraformVersion: ${{parameters.terraformVersion}}

- task: TerraformTaskV2@2
  displayName: Terraform Init
  name: TerraformInit
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: ${{parameters.terraformDirectory}}
    backendServiceArm: ${{parameters.backendSubscription}}
    backendAzureRmResourceGroupName: ${{parameters.backendResourceGroup}}
    backendAzureRmStorageAccountName: ${{parameters.backendStorageAccount}}
    backendAzureRmContainerName: ${{parameters.resourceName}}-${{parameters.environmentId}}
    backendAzureRmKey: ${{parameters.resourceName}}-${{parameters.environmentId}}.tfstate
