jobs:

- deployment: Deploy
  displayName: Deploy
  environment: Azure
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
  strategy:
    runOnce:
      deploy:
        steps:
          - template: /src/deployment/npm/steps/npm-package.steps.yaml