parameters:
  terraformDirectory: $(System.DefaultWorkingDirectory)
  terraformVersion: '' # Version of terraform to install
  environmentId: '' # Name of the environment in Azure. example qa, uat, production
  backendSubscription: '' # Subscription to store backend in
  backendResourceGroup: '' # Resource Group to store backend in
  backendStorageAccount: '' # Storage Account to store backend in
  environmentSubscription: '' # Subscription to provision resources in
  terraformInputVariables: [] # Object array of variables to set for Terraform; objects should have 'variableName' and 'variableValue' properties

steps:
  - template: /src/infrastructure/terraform/tasks/get-resource-name.yaml
    parameters:
      terraformDirectory: ${{ parameters.terraformDirectory }}

  - ${{ each variable in parameters.terraformInputVariables }}:
    - template: /src/infrastructure/terraform/tasks/set-variable.yaml
      parameters:
        terraformDirectory: ${{ parameters.terraformDirectory }}
        variableName: ${{ variable.variableName }}
        variableValue: ${{ variable.variableValue }}

  - template: /src/infrastructure/terraform/tasks/create-storage.yaml
    parameters:
      storageContainerName: $(ResourceName)-${{ parameters.environmentId }}
      subscription: ${{ parameters.backendSubscription }}
      backendStorageAccount: ${{ parameters.backendStorageAccount }}

  - template: /src/infrastructure/terraform/tasks/init.yaml
    parameters:
      terraformDirectory: ${{ parameters.terraformDirectory }}
      terraformVersion: ${{ parameters.terraformVersion }}
      environmentId: ${{ parameters.environmentId }}
      resourceName: $(ResourceName)
      backendSubscription: ${{ parameters.backendSubscription }}
      backendResourceGroup: ${{ parameters.backendResourceGroup }}
      backendStorageAccount: ${{ parameters.backendStorageAccount }}

  - template: /src/infrastructure/terraform/tasks/apply.yaml
    parameters:
      terraformDirectory: ${{ parameters.terraformDirectory }}
      environmentSubscription: ${{ parameters.environmentSubscription }}

  - template: /src/infrastructure/terraform/tasks/expand-variables.yaml
