parameters:
  - name: npmProjects   # Array of NPM projects to check
    type: object        # Provide an array containing objects of: { name: 'UI', path: 'folder/containing/package', suppressionsFilePath: 'optional/path/to/suppressions.xml' }
    default: []
  - name: dotnetSuppressionsFilePath # Path to the .NET suppressions.xml file
    type: string
    default: '$(Build.SourcesDirectory)/suppressions.xml'

jobs:

- job:
  displayName: Run Dependency Check

  steps:

  - template: /src/security/dependency-check/steps/dependency-check.steps.yaml
    parameters:
      npmProjects: ${{ parameters.npmProjects }}
      dotnetSuppressionsFilePath: ${{ parameters.dotnetSuppressionsFilePath }}