# Runs the EF Core migrations script for the provided DbContext on the provided SQL Server.
# Requires the following steps to have been run at an earlier stage in the pipeline.
# /src/deployment/efcore/tasks/build.yaml
# /src/deployment/efcore/tasks/publish.yaml
parameters:
  displayName: 'Migrate Azure SQL Database'
  artifactName: 'Migrations'
  dbContext: '' # Name of the DbContext
  azureSubscription: '' # Azure Subscription for the resource
  sqlHostname: '' # SQL Server Hostname
  sqlDatabase: '' # Database Name on the SQL Server
  sqlUser: '' # SQL Server Username
  sqlPassword: '' # SQl Server Password

steps:
  - task: SqlAzureDacpacDeployment@1
    displayName: ${{ parameters.displayName }}
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      AuthenticationType: 'server'
      ServerName: ${{ parameters.sqlHostname }}
      DatabaseName: ${{ parameters.sqlDatabase }}
      SqlUsername: ${{ parameters.sqlUser }}
      SqlPassword: ${{ parameters.sqlPassword }}
      deployType: 'SqlTask'
      SqlFile: $(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.dbContext }}.sql
      IpDetectionMethod: 'AutoDetect'
