# Publishes all EF Core migration scripts that have been built to an artifact.
# Requires /src/deployment/efcore/tasks/build.yaml to have been run at least once.
parameters:
  - name: displayName
    default: 'Publish EF Core Migration Scripts'
  - name: artifactName # The name of the build artifact to create.
    default: 'Migrations'

steps:
  - task: PublishBuildArtifacts@1
    displayName: ${{parameters.displayName}}
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Migrations'
      ArtifactName: ${{parameters.artifactName}}
    condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
