jobs:
- deployment: Deploy
  displayName: Deploy to NuGet (Public)
  environment: NuGet Public
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: /src/deployment/nuget/steps/public-nuget-package.steps.yaml