parameters:
  - name: serviceConnectionName # The name of the service connection used to deploy to Azure
    type: string
  - name: slotName # The name of the slot to deploy to, that will be swapped into production
    default: 'Staging'
  - name: resourceGroupName # The name of the resource group the app services are in
    type: string
  - name: appServices # The names of the app services to swap the slots in
    default: []
    type: object

steps:
  - task: AzureCLI@2
    displayName: 'Swap Slots'
    inputs:
      azureSubscription: ${{parameters.serviceConnectionName}}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $count = 0
        $direction = 1
        $ResourceNames = '${{convertToJson(parameters.appServices)}}' | ConvertFrom-Json;
        Do
        {
            try {
                $target = $ResourceNames[$count]
                "Starting ($count) $target"
                az webapp deployment slot swap -g '${{parameters.resourceGroupName}}' -n $target --slot ${{parameters.slotName}} --target-slot production | ConvertFrom-Json
                if (!$?) {
                    $direction = -1
                    "$target failed. Reverting previous slot swaps"
                }
                else {
                    "Completed ($count) $target successfully"
                }
            }
            finally {
                $count = $count + $direction
            }
        } while (($count -gt -1) -and ($count -lt $ResourceNames.count))
        if ($count -lt 0) {
            write-error "failed slot swapping"
            exit 1
        }
        else {
            exit 0
        }
